language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
install:
  - tools/composer.phar install
script:
  - tools/phpunit.phar
notifications:
  email:
    recipients: [ travis@fabrizio-branca.de ]
    on_success: always
    on_failure: always