language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
script:
  - tools/phpunit.phar
notifications:
  email:
    recipients: [ fabrizio.branca@aoe.com ]
    on_success: always
    on_failure: always